apiVersion: v1
kind: Service
metadata:
  name: backend-api-user
  labels:
    run: backend-api-user
spec:
  ports:
  - port: 8080
    name: "8080"
    targetPort: 8080
  selector:
    run: backend-api-user
    